use serde::{
    de::DeserializeOwned,
    Deserialize,
};
use tauri::{
    plugin::{PluginApi, PluginHandle},
    AppHandle, Runtime,
};

use crate::models::*;
use serde_json::Value;

#[cfg(target_os = "ios")]
tauri::ios_plugin_binding!(init_plugin_sharetarget);

/// Access to the sharetarget APIs.
pub struct ShareTarget<R: Runtime>(PluginHandle<R>);

///  ShareTarget methods. Note that `ShareTarget::registerListener()` will be autogenerated.
impl<R: Runtime> ShareTarget<R> {
    /// A simple ping function. Just lets you know the plugin is still alive.
    pub fn ping(&self, payload: PingRequest) -> crate::Result<PingResponse> {
        self
            .0
            .run_mobile_plugin("ping", payload)
            .map_err(Into::into)
    }
pub fn get_initial_share(&self) -> crate::Result<GetInitialShareResponse> {
    // 1. 先把原始 JSON 拿出来
    let raw: Value = self
        .0
        .run_mobile_plugin::<Value>("getInitialShare", ())?;

    // 2. 打印出来看看到底长啥样
    println!("raw getInitialShare response = {raw}");

    // 3. 再手动反序列化成你的 enum
    let response: MobileGetInitialShareResponse =
        serde_json::from_value(raw)
            .expect("failed to deserialize MobileGetInitialShareResponse");

    Ok(response.into_option())
}
}

/// Initialize the Kotlin class attached to this plugin.
pub fn init<R: Runtime, C: DeserializeOwned>(
    _app: &AppHandle<R>,
    _api: PluginApi<R, C>,
) -> crate::Result<ShareTarget<R>> {
    let handle = _api.register_android_plugin("app.tauri.sharetarget", "ShareTargetPlugin")?;

    Ok(ShareTarget(handle))
}

/// Internal helper to accept the Android plugin payload either as a populated ShareEvent
/// or an "empty" JSON value (null/object) indicating no data.
#[derive(Debug, Deserialize)]
#[serde(untagged)]
enum MobileGetInitialShareResponse {
    Share(ShareEvent),
    Empty(Value),
}

impl MobileGetInitialShareResponse {
    fn into_option(self) -> Option<ShareEvent> {
        match self {
            MobileGetInitialShareResponse::Share(event) => Some(event),
            MobileGetInitialShareResponse::Empty(_raw) => None,
        }
    }
}
